### ISSUE TITLE
Certificate Problem of APPX File

### ISSUE THREAD

**Issue by BaymaxShao** [SitronSch/FnO-Hololens2-visualisation#11]
I try installing the app on HoloLens 2 with release appx file. However, I meet the error:

Unable to verify the publisher certificate for this application package. Please contact your system administrator or application developer to obtain a new application package with a verification certificate. The root certificate and all direct certificates (0x800B010A) signed in the application package must be verified

Maybe there is a problem of certificate in the APPX File.

**Comment by SitronX** [comment]
Hello @BaymaxShao  can you try this process as is described [here](https://stackoverflow.com/questions/23812471/installing-appx-without-trusted-certificate)?  I think the process of adding certificate will be very similar, if not the same on Hololens 2 device.

Originally there was visual studio project included in release section, so you could build it yourself (you still can) but later switched for this appx as some user asked for this. For this you probably have to manually choose to trust the file certificate and it should work normally after.

Although just to note. There are two versions of the app. One with volume rendering and second with model rendering. The one you are talking about uses model rendering, but main focus was primarily given to volume rendering app that uses remote connection with headset and PC.

**Comment by BaymaxShao** [comment]
Thank you for your suggestion! It works!
However, I meet a new problem. When I open the menu, the menu seems very far from me, shown as below:
![20240412_071047_HoloLens](https://github.com/SitronX/FNO-Hololens2-visualisation/assets/91866296/38cdfbdb-5ea9-4423-9dab-38d2efac14bb)
I guess the menu is in the red circle, because when I show my palm to the camera or give the voice commands to HoloLens, it has no reaction.

**Comment by SitronX** [comment]
Hello @BaymaxShao.
On this version of the app (with models) there is no hand menu. Hand menu is only in volume rendering app. To see the model, scan any qr code near you, the model with control panel will then be placed nearby.

**Comment by shiauyang** [comment]
Hi, @SitronX ,
I scan QR code from https://github.com/SitronX/FNO-Hololens2-visualisation/blob/VolumetricData/Assets/Images/qr-code-icon.png, however, the menu is still far from my me.

**Comment by SitronX** [comment]
@shiauyang Hello,
are you using Volumetric or Model version? It is possible that i forgot to turn off the hand menu in model version, so it appears far away, but it is still non functional in model version. The hand menu is only functional in Volumetric version.

**Comment by shiauyang** [comment]
God @SitronX,

Firstly, I use Models.Hololens2.-.standalone.self.contained.1.0.appx from All build 1.0, so if QR code cannot call menu, how to use this version? Cause I can't do anything. 

Secondly, it seems like Volumetric version needs to use Unity to build by myself?

Lastly, I put some abdomen segment (.obj) files in Hololens2, however the FPS of it is about 20 Hz (target FPS is 60 Hz). Do you have any suggestions? I have already used URP in Hololens2 and tried to reduce mesh size, so I was now thinking about using computer to render and then pass to Hololens2 through internet like your majestic project. Please give me some advises; it will help me a lot.

Thanks, God @SitronX

**Comment by SitronX** [comment]
Hello @shiauyang .
First, please read [this comment](https://github.com/SitronX/FNO-Hololens2-visualisation/issues/11#issuecomment-2052150788). Everything else is described on its model branch [here](https://github.com/SitronX/FNO-Hololens2-visualisation/tree/Models), where you'll also find a complete step-by-step guide on how to use the model version. Just to note, majority of the development time was spent in volumetric version, model version is not as complete as volumetric one.

To use Volumetric version without building, visit [Releases](https://github.com/SitronX/FNO-Hololens2-visualisation/releases/tag/1.1) page, download the release, unzip it, and launch the executable (more information can be also found [here](https://github.com/SitronX/FNO-Hololens2-visualisation?tab=readme-ov-file#running-the-app). A complete step-by-step guide for adding new datasets to the Volumetric version is available [here](https://github.com/SitronX/FNO-Hololens2-visualisation?tab=readme-ov-file#working-with-new-datasets).

> Lastly, I put some abdomen segment (.obj) files in Hololens2, however the FPS of it is about 20 Hz 

The step-by-step video I mentioned [earlier](https://github.com/SitronX/FNO-Hololens2-visualisation/tree/Models?tab=readme-ov-file#manual) also explains how to reduce the polygon count in Blender to a reasonable level. 

Since this is unrelated to the certificate issue, I will close this issue. If you encounter any further issues, please make sure to review the readme documentation (which I spent considerable time creating). If anything is still unclear, feel free to open a new issue related to the specific topic and I will try my best to help you.
