### ISSUE TITLE
Compiled HoloLens APPX file

### ISSUE THREAD

**Issue by Tony-j77** [SitronSch/FnO-Hololens2-visualisation#5]
Hello! I was wondering if you could provide the compiled file for the HoloLens 2? I was hoping to try this software but it seems like I am having some troubles building project in visual studio.

**Comment by SitronX** [comment]
Hello @Tony-j77 ,
I have updated the [release section](https://github.com/SitronX/FnO-Hololens2-visualisation/releases/tag/1.0) to have appx file instead of Visual Studio project. The compiled appx file now should be sideloadable to Hololens 2.

Although just to note. There are two versions of the app. One with volume rendering and second with model rendering. The one you are talking about uses model rendering, but main focus was primarily given to volume rendering app that uses remote connection with headset and PC.
